### ISSUE TITLE
Panic not recovered

### ISSUE THREAD

**Issue by mayur-tolexo** [dgrr/GoSlaves#5]
Hi!
What if there is a panic while serving the request by goroutines?

**Comment by dgrr** [comment]
Can you paste the panic trace here?

**Comment by mayur-tolexo** [comment]
Changed your test case a little bit to create panic.
![Screenshot 2019-06-07 at 7 22 27 PM](https://user-images.githubusercontent.com/20511920/59108898-9c5dd300-8959-11e9-9e2f-17cf380af04c.png)


![Screenshot 2019-06-07 at 7 10 39 PM](https://user-images.githubusercontent.com/20511920/59108861-8819d600-8959-11e9-8784-d86fccc151dd.png)

**Comment by mayur-tolexo** [comment]
The idle scenario is that the job due to which panic has occured will be logged and the worker will continue doing the next job.

**Comment by dgrr** [comment]
Aha, so you say that the panic cannot be recovered?

**Comment by mayur-tolexo** [comment]
no, I was saying, Your worker repo should be handling the panic and there should be recovered for each job performed by the workers.

**Comment by dgrr** [comment]
No. It would decrease the performance and also it's not a matter of the package. I want to keep this package as simple as possible in order to have the best performance for little jobs. It's not intended to handle panics, this is a matter the user should handle by their own. Unless you give me a good reason to change this...

**Comment by mayur-tolexo** [comment]
if you want it that simple then it can be done in few lines:
```
func main() {
	rounds := 100000
	ch := make(chan interface{}, rounds)
	go executeServe(ch, rounds/2)
	go executeServe(ch, rounds/2)
	i := 0
	for i < rounds {
		select {
		case job := <-ch:
			fmt.Println(job)
			i++
		}
	}
}

func executeServe(ch chan interface{}, rounds int) {
	for i := 0; i < rounds; i++ {
		ch <- i
	}
}
```

**Comment by mayur-tolexo** [comment]
See this id 2.5 times faster. But there is no point of this as this won't provide other functionalities.
![Screenshot 2019-06-07 at 8 29 27 PM](https://user-images.githubusercontent.com/20511920/59113633-07f86e00-8963-11e9-9930-7e8023290506.png)

**Comment by dgrr** [comment]
Can you post here the code of the benchmark you made?

**Comment by mayur-tolexo** [comment]
Ya sure.
```
package slaves

import (
	"testing"
)

func BenchmarkMDPool(b *testing.B) {
	ch := make(chan interface{}, b.N)
	go executeServe1(ch, b.N)
	i := 0
	for i < b.N {
		select {
		case <-ch:
			i++
		}
	}
}

func executeServe1(ch chan interface{}, rounds int) {
	for i := 0; i < rounds; i++ {
		ch <- i
	}
}

```

**Comment by dgrr** [comment]
Yep, I mean, I want to keep the package simple. I don't want to add panic recovery because if you want to make something simple and quickly you don't need to execute recover() every time. I think it's a matter of the user to use it or not.

**Comment by mayur-tolexo** [comment]
Ok great.
Can you please checkout: [sworker](https://mayur-tolexo.github.io/sworker/)
Can you suggest if I am missing any feature?

Basic print job using two workers.  
```
//print : function which worker will call to execute
func print(ctx context.Context, value ...interface{}) error {
	fmt.Println(value)
	return nil
}

func main() {
	pool := draught.NewSimplePool(n) //new job pool created
	pool.AddWorker(2, print, true) //adding 2 workers
	for i := 0; i < 100; i++ {
		pool.AddJob(i) //adding jobs
	}
	pool.Close() //closing the job pool
}
```

**Comment by mayur-tolexo** [comment]
Hey buddy. I have done the benchmarking. Yours is much faster in case of more CPU by don't provide many functionalities.

![Screenshot 2019-06-11 at 12 41 43 AM](https://user-images.githubusercontent.com/20511920/59220202-07b9d600-8be2-11e9-8571-6575fbde3610.png)

**Comment by dgrr** [comment]
Yep, yours is fast enough having that many features
